### ISSUE TITLE
The command loadchunk is always failed

### ISSUE THREAD

**Issue by JinxLbj** [RedisBloom/RedisBloom#107]
It's successful when i load first cursor "0". But It's always Couldn't load chunk when the second cursor

**Comment by mnunberg** [comment]
Can you show an example usage? You need to pass the tuples as received from SCANDUMP

**Comment by JinxLbj** [comment]
> Can you show an example usage? You need to pass the tuples as received from SCANDUMP

I hava figured out this problem, When i get the byte[] from SCANDUMP, i use SafeEncoder to convert it to String. And I convert it to byte[] again when i want to LOADCHUNK. It may destory the data.
Finally i try not to convert it. It's return OK
