### ISSUE TITLE
How to Use RedisBloom in PHP?

### ISSUE THREAD

**Issue by zhoutingze** [RedisBloom/RedisBloom#108]

**Comment by ashtul** [comment]
You can use any Redis PHP client and pass full Redis commands to it.
For example, you can use PhpRedis's [rawCommand](https://github.com/phpredis/phpredis#rawcommand) as 

1. $redis->rawCommand("BF.RESERVE", "bf", "0.001", 1000)
2. $redis->rawCommand("BF.ADD", "bf", "RedisLabs")
3. $redis->rawCommand("BF.EXISTS", "bf", "RedisLabs")

**Comment by zhoutingze** [comment]
> You can use any Redis PHP client and pass full Redis commands to it.
> For example, you can use PhpRedis's [rawCommand](https://github.com/phpredis/phpredis#rawcommand) as
> 
> 1. $redis->rawCommand("BF.RESERVE", "bf", "0.001", 1000)
> 2. $redis->rawCommand("BF.ADD", "bf", "RedisLabs")
> 3. $redis->rawCommand("BF.EXISTS", "bf", "RedisLabs")

thanks.
