### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by e271828-** [RedisBloom/RedisBloom#116]
Why was the license changed from Apache 2.0? 

This is simply an implementation of common data structures on top of a BSD 3-clause daemon, and its main utility is as a template for people to build their own modules. That utility is eliminated with the bizarro proprietary license.

From the star count it appears to have almost no users, so it is not like there was a large captive corporate audience to lock in here.

**Comment by K-Jo** [comment]
Hi @e271828, for more information of our licensing, I refer you to https://redislabs.com/community/licenses/ and https://redislabs.com/blog/redis-labs-modules-license-changes/.  Let me know if we can close this issue.

**Comment by e271828-** [comment]
Ah, didn't even notice the commons clause modification of previous Apache 2.0. 

For what it's worth, I can't imagine a rational company of any size would use this under either license. Rewriting from scratch would cost less than the legal review.

If you have some internal tracker for the number of times people complain about module licensing then please increment it as you close this issue.

**Comment by K-Jo** [comment]
@e271828- I regret to hear you would consider other alternatives.  The license is actually very permissive but tries to protect us, as an open source company, from companies who would like to sell the database as a service and compete with us without contributing back to the open source / source available repositories. You are free to use it for your own usage, as part of your business, embed it in products, as long as you don't offer it as a service.  On top of that I would like to add that several open source database companies are taking the same approach of source available licenses.

to be more precise, here's the summary of the license:
```
RSAL is a software license created by Redis Labs for certain Redis Modules running on top of open source Redis. RSAL grants equivalent rights to permissive open source licenses for the vast majority of users. With RSAL, developers can use the software, modify the source code, integrate it with an application, and use, distribute or sell the application. The only restriction is that the application cannot be a database, a caching engine, a stream processing engine, a search engine, an indexing engine or an ML/DL/AI serving engine.
```

**Comment by e271828-** [comment]
> ```
> The only restriction is that the application cannot be a database, a caching engine, a stream processing engine, a search engine, an indexing engine or an ML/DL/AI serving engine.
> ```

This is an absurdly broad set of services. The license itself has this definition:

> Database Product: any of the following products or services: (a) database; (b) caching engine; (c)
stream processing engine; (d) search engine; (e) indexing engine; (f) machine learning or deep
learning or artificial intelligence serving engine; (g) a product or service exposing the Redis API; (h) a
product or service exposing the Redis Modules API; or (i) a product or service exposing the Software
API. 

Thousands of non-database SaaS businesses fall under b-f, or have them as a component of their offerings.

One particular implementation of a data structure invented in 1970 is critical IP to none of them. A redis module is at most an operational convenience, as some will have redis already in production. 

Anyway, this conversation is probably not a great use of time for either of us. Feel free to close this ticket.
