### ISSUE TITLE
Is there anyway to lower the command

### ISSUE THREAD

**Issue by WTIFS** [RedisBloom/RedisBloom#145]
When typing "command" in redis-cli, it returns bloom commands with uppercase, which is different from redis built-in commands.

```bash
redis-cli > command
redis-cli >
 93) 1) "CF.MEXISTS"
     2) (integer) -1
     3) 1) readonly
        2) fast
     4) (integer) 1
     5) (integer) 1
     6) (integer) 1
 94) 1) "BF.LOADCHUNK"
     2) (integer) -1
     3) 1) write
        2) denyoom
     4) (integer) 1
     5) (integer) 1
     6) (integer) 1
 95) 1) "zremrangebylex"
     2) (integer) 4
     3) 1) write
     4) (integer) 1
     5) (integer) 1
     6) (integer) 1
 96) 1) "xlen"
     2) (integer) 2
     3) 1) readonly
        2) fast
     4) (integer) 1
     5) (integer) 1
     6) (integer) 1
```

Is there anyway to make the redis to return lowercase bloom commands?

**Comment by ashtul** [comment]
@gkorland @itamarhaber @MeirShpilraien

**Comment by ashtul** [comment]
@WTIFS 
If you look in our code at rebloom.c, you can see we register the commands in RedisModule_OnLoad function and the letter case is whatever the programmer used.
Out of curiosity, is there any place where you face any issue with it? The module should be able to handle both.

**Comment by WTIFS** [comment]
@ashtul I see, thanks.  I'm just wondering if it's better to keep the case of redis bloom commands same as the built-in commands.

I'm facing this problem in golang's redis library[ go-redis](https://github.com/go-redis/redis). It uses lowercase to check whether a redis command exists, thus failed to find out the redis bloom commands. I totally agree that the module should handle both, and actually I submitted a pull request to add the lowercase support, but no response yet.

**Comment by ashtul** [comment]
@gkorland shell we change to lower case and standardize it across modules?

**Comment by ashtul** [comment]
@WTIFS 
Lowercased commands in now merged into master.
Thank you for this input.

**Comment by WTIFS** [comment]
> @WTIFS
> Lowercased commands are now merged into master.
> Thank you for this input.

Awesome. Thanks!
