### ISSUE TITLE
why delay raise in the first several request after stop request several minutes？

### ISSUE THREAD

**Issue by yandc** [RedisBloom/RedisBloom#162]
In my performance test, the first several request(madd/mexists, 20 keys each request) reach a high latency(about 20ms), after then, the latency lower than 1ms. This behavior repeat again if i stop request several minutes.

**Comment by ashtul** [comment]
@yandc Can you please share some more details?
Which filter are you asking about? which client are you using?

**Comment by yandc** [comment]
@ashtul I'm using bloom filter,  using booredis(c++ client) and redis-cli(bash command) confirmed my result. This seems data was readed from disk and cached, several minutes later cache expired. confusing...

**Comment by yandc** [comment]
> @yandc Can you please share some more details?
> Which filter are you asking about? which client are you using?

**Comment by ashtul** [comment]
Can you please share the code you are using?

**Comment by yandc** [comment]
> Can you please share the code you are using?

first, open a bloom filter with command bf.reserve test01 0.00001 1600000000 (my memory is enough)

second, set and check with loop:
36|     for(int i = 0; i < loop; i++) {
37|         if(i%100000 == 0) cout << i << " set time: " << get_time_ms()-t1 << endl;
38|         keys.clear();
39|         for(int j = 0; j < 20; j++) {
40|             snprintf(buf, 128, "%s_%d_%d", argv[4], i, j);
41|             keys.push_back(buf);
42|         }
43|         ret = client.setKeys(argv[3], keys);//join each key with prefix argv[3], and send command bf.madd test01 keys
44|         if(ret != 0) {
45|             cout << "set keys error, %d" << i << endl;
46|         }
47|     }
48|     t2 = get_time_ms();
49|
50|     /*read*/
51|     vector<bool> result;
52|     for(int i = 0; i < loop; i++) {
53|         if(i%100000 == 0) cout << i << " check time: " << get_time_ms()-t2 << endl;
54|         result.clear();
55|         keys.clear();
56|         for(int j = 0; j < 10; j++) {
57|             snprintf(buf, 128, "%s_%d_%d", argv[4], i, j);
58|             keys.push_back(buf);
59|             snprintf(buf, 128, "%s_%d_%d", argv[4], i, j+20);
60|             keys.push_back(buf);
61|         }
62|         client.checkKeys(result, argv[3], keys);//join each key with prefix argv[3] and send commannd bf.mexists test01 keys
63|         if(result.size() != 20) {
64|             cout << "result size error: %d" << result.size() << endl;
65|             continue;
66|         }
67|         for(int j = 0; j < 10; j++) {
68|             if(result[j*2] != true) {
69|                 cout << "check keys error, " << i << "_" << j << " " << result[j*2] << endl;
70|             }
71|             if(result[j*2+1] != false) {
72|                 cout << "check keys error, " << i << "_" << j << " " << result[j*2+1] << endl;
73|             }
74|         }
75|     }
@ashtul

**Comment by yandc** [comment]
The latency raise when a new big bloom block created, after hundreds of key add, latency decrease down to normal.
I guess, the first hundreds request trigger page fault and initialize memory, leads to latency raise.

**Comment by ashtul** [comment]
This is what I suspected. 
I’ve requested @filipecosta90 to review it as well.

**Comment by ashtul** [comment]
@yandc 
The problem is not just page faults but the memory allocation and initialization to `0`.

Adding the following code in `bloom_init` function in `contrib/bloom.c` after memory was allocated will resolve the letancy you experience.
```
for (size_t i = 0; i < bloom->bytes; i += 4000) {
    bloom->bf[i] = 0; // force system to allocate all memory
}
```
We will consider making this change in our code or possibly adding a flag to enable this function but at the moment, we are not going to change the behavior.
You can compile the code yourself with these changes.
