### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by averias** [RedisBloom/RedisBloom#165]
Hi RedisBloom maintainers,

I just noticed that you are pushing changes to master which are incompatible with your `redislabs/rebloom:latest` docker image as you are pointing out in the [documentation](https://oss.redislabs.com/redisbloom/Quick_Start/#launch-redisbloom-with-docker), so probably you should update the documentation so in that way, people that are using, or testing first-time RedisBloom with this Docker image will not have issues since now there are some changes like:
- CMS.INCRBY returns now a count of each item after incrementing instead of OK as before
- There are new EXPANSION and NONSCALING optional params in BF.RESERVE and BF.INSERT 

which are not gonna work in the `latest` version but do work in the `edge` one.

Anyway, and IMHO you could probably keep a develop (or edge) branch where you could push all the changes you are working on for a new release and then deploy to master the new release following semantic versioning.  `redislabs/rebloom:edge` could reflect all the PRs you merged in develop branch and `redislabs/rebloom:latest` be synced with master.

That would be great for several reasons:
- for the ones who are maintaining clients in different languages, like me, we could keep track of your changes for the next release in that develop branch and work at the same time in a new release of our library
- you/we could detect possible issues in the develop branch before moving to master
- you could solve the inconsistency between installing RedisBloom as a module where you have the latest changes (master branch) and using the latest Docker image which is not updated with the master branch

It is just a suggestion, but please let me know if you are able to do the above, otherwise, I will specify it clearly in the documentation of `phpredis-bloom`.

Regards

**Comment by ashtul** [comment]
@averias 
First I want to Thank you for your detail comment.

We are going to tag a new version in the coming days and this is part of this change. I apologize for the inconvenience.

To your points -
* The CMS change indeed breaks the API. This PR was waiting for a minor version for several months now. We make sure to not break API on smaller patch releases.
* I'm happy you noticed the changes in Bloom and Cuckoo configuration. They will allow developers more control of their filters. They do not break the API.

Please let me know if there is anything else I can assist with.

**Comment by averias** [comment]
@ashtul thank you so much for your quick answer and happy to know you are gonna tag a new version in the next days, so `latest` and `edge` docker images will be synced. 

Anyway, please consider, if possible, to follow that gitflow I explained in my previous post, so you as maintainers, contributors and the ones we are implementing clients for RedisBloom we can all test new features previously to final releases in `edge` docker image and also, IMHO, it makes more sense to have `develop` branch in `edge` docker image and `master` branch in `latest` image, so users of RedisBloom will get same updates by either pulling `latest` image or install it as module and we can use `edge` docker image for testing and environment for implementing client updates.

Kind regards and thank you again!

**Comment by ashtul** [comment]
@averias 
Thank you again for your comment. We have added an unstable version. #166

**Comment by averias** [comment]
that is great @ashtul! Thank you for the feedback
