### ISSUE TITLE
when i use command INSERT, my filter always change an new filter

### ISSUE THREAD

**Issue by JinxLbj** [RedisBloom/RedisBloom#171]
CF.DEBUG realtimeFeedFilter
"bktsize:2 buckets:536870912 items:0 deletes:0 filters:1"
"bktsize:2 buckets:536870912 items:532 deletes:0 filters:1"
"bktsize:2 buckets:536870912 items:1026 deletes:0 filters:1"
....
"bktsize:2 buckets:512 items:722 deletes:0 filters:1"

My Filter change to an new Instance

CF.ADD has same problem too

CF.INSERTNX is ok

**Comment by ashtul** [comment]
@JinxLbj can you please provide full list of commands. What commands do you use?

**Comment by JinxLbj** [comment]
> @JinxLbj can you please provide full list of commands. What commands do you use?
CF.RESERVE realtimeFeedFilter 1073741824
CF.ADD realtimeFeedFilter somedata1
CF.ADD realtimeFeedFilter somedata2
CF.ADD realtimeFeedFilter somedata3
...
CF.ADD realtimeFeedFilter somedatan
CF.DEBUG realtimeFeedFilter
"bktsize:2 buckets:512 items:722 deletes:0 filters:1"

**Comment by JinxLbj** [comment]
> @JinxLbj can you please provide full list of commands. What commands do you use?

When i use CF.INSERT NOCREATE replace CF.ADD
My key has disappeared

**Comment by ashtul** [comment]
Can you provide more details? Maybe the script you’re using. 
What version of RedisBloom are you using?
Are you getting any false-negatives?

**Comment by ashtul** [comment]
@JinxLbj 
Can you please provide more details?
When do you query `CF.DEBUG realtimeFeedFilter`?
Can you provide complete script of how this bug can be reproduced?

**Comment by JinxLbj** [comment]
> @JinxLbj
> Can you please provide more details?
> When do you query `CF.DEBUG realtimeFeedFilter`?
> Can you provide complete script of how this bug can be reproduced?

Sorry, it's so late to reply and my english isn't fluent
I seemly found the source.
I use the command to create a filter:
CF.RESERVE testFilter 1073741824
And I use the command for 5 time, It's OK:
CF.INSERT testFilter NOCREATE ITEMS 860341046659204,577436804613
But when i do it at the 6 time:
"ERR not found"
My Filter is disappeard, And my Other key has disappeard too.
It't seem My redis is broken up

**Comment by ashtul** [comment]
@JinxLbj 
I have tried to reproduce the error you mention but it seems to work well.
Can you please check which version do you use? Alternatively, can you try to test it again on docker image? You can run it like this `docker run -p 6379:6379 redislabs/rebloom:latest`

**Comment by JinxLbj** [comment]
@ashtul 
It's ok on docker.
It looks like an environment error.
My failed environment is :
Red Hat 4.8.5-16
Redis 5.0.5
But i don't know what the bloom version is.
And I try again on my failed environment,I used lastest bloom.
It failed on the 12-14 time when i insert.
It's too strange

**Comment by ashtul** [comment]
@JinxLbj 
For your knowledge, ADDNX and INSERTNX are inherently different than ADD and INSERT. They check for an item before and only if the query returns as negative, they insert it. This prevent keeping multiple copies of the same fingerprint but disallows the deletion of elements since it will introduce false-negative errors.

**Comment by JinxLbj** [comment]
@ashtul 
we just figure out this question.
Too more same elements will let the filter expend.
It lead to my redis has not enough space and used "all-lru" strategy.
Thanks for your help.

**Comment by ashtul** [comment]
@JinxLbj 
Happy to hear that.
Please feel free to contact me with any further inquiry.
