### ISSUE TITLE
bf command is disabled when I set password for redisbloom using requirepassword

### ISSUE THREAD

**Issue by 18705320883** [RedisBloom/RedisBloom#172]
start rebloom  using 
 docker run -d --name bloomfilter -p 6379:6379 redislabs/rebloom --requirepass "aaa"
then redis-cli,I can not  use bf.add

**Comment by gkorland** [comment]
@18705320883 can you please add the error you're getting?

**Comment by 18705320883** [comment]
start docker with 
docker run -d --name bloomfilter -p 6379:6379 redislabs/rebloom --requirepass "yhf"
bf.add abc c1
(error) ERR unknown command `bf.add`, with args beginning with: `abc`, `c1`,

**Comment by averias** [comment]
Are you executing `redis-cli` from inside the container?

$ docker run -d --name bloomfilter -p 6379:6379 redislabs/rebloom
Unable to find image 'redislabs/rebloom:latest' locally
latest: Pulling from redislabs/rebloom
000eee12ec04: Already exists 
5cc53381c195: Already exists 
48bb7bcb5fbf: Already exists 
ef8a890bb1c2: Already exists 
32ada9c6fb0d: Already exists 
76e034b0f296: Already exists 
a6aadb5ece2a: Pull complete 
79dd6d78325e: Pull complete 
Digest: sha256:10b5693ff50e55cbd78f44856c0de941e8bf939981b34dbeb6c49be358f031b5
Status: Downloaded newer image for redislabs/rebloom:latest
2076a50009fcc385cd259dd9c32df6bf420e878a55c54e8eb1fc7a66baed720a

$ docker exec -it bloomfilter bash
root@2076a50009fc:/data# redis-cli
127.0.0.1:6379> bf.add abc c1
(integer) 1
127.0.0.1:6379> keys *
1) "abc"
127.0.0.1:6379>

for me, it is working

**Comment by 18705320883** [comment]
you did not set password or override any setting

**Comment by 18705320883** [comment]
bloom does not support authentication ?

**Comment by 18705320883** [comment]
docker exec -it redis redis-cli -a yhf
by this command it is ok
but  auth is not

**Comment by averias** [comment]
I think it is an issue with the image, I tested with my local redis instance, I enabled authentication in `redis.conf`, then I connected with `redis-cli -a mypassword` and all it's ok:

127.0.0.1:6379> bf.add abc c1
(integer) 1
127.0.0.1:6379> keys *
1) "abc"

**Comment by lihsai0** [comment]
@18705320883 You override loadmoudle cmd. Try this:

``` bash
docker run -d \
  --name bloomfilter \
  -p 6379:6379 \
  redislabs/rebloom \
  redis-server \
  --loadmodule "/usr/lib/redis/modules/redisbloom.so" \
  --requirepass "yhf"
```

**Comment by linupychiang** [comment]
> start rebloom using `docker run -d --name bloomfilter -p 6379:6379 redislabs/rebloom` then redis-cli, execute `config set requirepass "xxx"` then `bf.add` is work!

it works for me! @Roc-Chan
