### ISSUE TITLE
what mean sub-filter ??

### ISSUE THREAD

**Issue by startjava** [RedisBloom/RedisBloom#173]
please tell me it more ! thank you very much!

**Comment by ashtul** [comment]
@startjava 
Thank you for your question.
I have expanded the documentation to better explain sub-filters.
In short, a scalable bloom filter is initialized with one sub-filter and when it is full (at 50% fill rate), a second sub-filter is added to it and all inserts are going to the second filter. When querying, both sub-filters will be tested.
