### ISSUE TITLE
BloomFilter - (error) ERR bad capacity

### ISSUE THREAD

**Issue by w1614067865** [RedisBloom/RedisBloom#184]
BF.RESERVE customFilter 0.01 5000000000
(error) ERR bad capacity

**Comment by ashtul** [comment]
Hello 
Can you confirm you are using the most recent version of RedisBloom. I have just tested it and it worked as expected.
We have allowed for higher capacity in PR #179. Is there a possibility you are using an older version?
```
127.0.0.1:6379> BF.RESERVE customFilter 0.01 5000000000
OK
127.0.0.1:6379> BF.INFO customFilter
 1) Capacity
 2) (integer) 5000000000
 3) Size
 4) (integer) 6892346039
 5) Number of filters
 6) (integer) 1
 7) Number of items inserted
 8) (integer) 0
 9) Expansion rate
10) (integer) 2
```

**Comment by w1614067865** [comment]
Hello, I am using the Docker version of RedisBloom
docker run -p 6379:6379 --name redis-redisbloom redislabs/rebloom:latest

**Comment by w1614067865** [comment]
> 您好，是否
> 可以确认您使用的是RedisBloom的最新版本。我刚刚测试了它，并且按预期工作。
> 我们在PR [＃179中](https://github.com/RedisBloom/RedisBloom/pull/179)允许更高的容量。您使用的是旧版本吗？
> 
> ```
> 127.0.0.1:6379> BF.RESERVE customFilter 0.01 5000000000
> OK
> 127.0.0.1:6379> BF.INFO customFilter
>  1) Capacity
>  2) (integer) 5000000000
>  3) Size
>  4) (integer) 6892346039
>  5) Number of filters
>  6) (integer) 1
>  7) Number of items inserted
>  8) (integer) 0
>  9) Expansion rate
> 10) (integer) 2
> ```

Hello, I am using the Docker version of RedisBloom
docker run -p 6379:6379 --name redis-redisbloom redislabs/rebloom:latest

**Comment by ashtul** [comment]
Indeed, PR #180 which remove the limit was not included in the latest PR.
While we tag and release a new minor version I would suggest you use `docker run -p 6379:6379 --name redis-redisbloom redislabs/rebloom:edge`
Regards

**Comment by w1614067865** [comment]
> 实际上，删除限制的PR [＃180](https://github.com/RedisBloom/RedisBloom/pull/180)未包含在最新的PR中。
> 在标记并发布新的次要版本时，建议您使用`docker run -p 6379:6379 --name redis-redisbloom redislabs/rebloom:edge`
> Regards


ok, thank you very much
