### ISSUE TITLE
docker restart redis error

### ISSUE THREAD

**Issue by w1614067865** [RedisBloom/RedisBloom#195]
1:M 01 Apr 2020 14:31:57.944 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 01 Apr 2020 14:31:57.944 # Server initialized
1:M 01 Apr 2020 14:31:57.944 * Module 'bf' loaded from /user/local/etc/redis/modules/redisbloom.so

1:M 01 Apr 2020 14:32:25.962 # Error loading data from RDB (short read or EOF). Read performed by module 'bf' about type 'MBbloom--' after reading '0' bytes of a value.

1:C 01 Apr 2020 14:32:51.278 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 01 Apr 2020 14:32:51.278 # Redis version=5.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 01 Apr 2020 14:32:51.278 # Configuration loaded

**Comment by ashtul** [comment]
@w1614067865 
Can you please share the RDB file?

**Comment by gkorland** [comment]
@w1614067865 did you manage?

**Comment by ashtul** [comment]
No followup
