### ISSUE TITLE
BF.DEBUG  bytes is the key size?

### ISSUE THREAD

**Issue by wujinbiao94** [RedisBloom/RedisBloom#211]
BF.DEBUG myfilter1 result is as follows
1) "size:1"
2) "bytes:51532 bits:412256 hashes:15 hashwidth:64 capacity:20000 size:1 ratio:5e-05"

bytes is the key size?
But I user redis-memory-for-key ,result is as follows
redis-memory-for-key myfilter1
Key				myfilter1
Bytes				763
Type				module

**Comment by ashtul** [comment]
Size is the number of elements you have inserted into the filter.
About the discrepancy with `redis-memory-for-key`, need to check.

**Comment by wujinbiao94** [comment]
> Size is the number of elements you have inserted into the filter.
> About the discrepancy with `redis-memory-for-key`, need to check.

I know Size.
I want to know what bytes in "2.bytes:51532 bits:412256 hashes:15 hashwidth:64 capacity:20000 size:1 ratio:5e-05" mean.Is it the actual memory size or the calculated theoretical value?

**Comment by ashtul** [comment]
bytes is the actual size that is used when the memory was allocated
