### ISSUE TITLE
Use RedisBloom for URLs deduplication?

### ISSUE THREAD

**Issue by starzou** [RedisBloom/RedisBloom#232]
Hello guys.

**About 2 billion URLs,** 

**Should one bloom filter or multiple bloom filters be created?**
**How much memory will this need to use?**

Thanks to all contributors.

**Comment by starzou** [comment]
I got it thanks.

**Comment by starzou** [comment]
For reference only:


```
127.0.0.1:6379> BF.RESERVE urls 0.01 100
OK
127.0.0.1:6379> BF.DEBUG urls
1) "size:0"
2) "bytes:138 bits:1104 hashes:8 hashwidth:64 capacity:100 size:0 ratio:0.005"
```

```
127.0.0.1:6379> BF.RESERVE urls 0.001 100
OK
127.0.0.1:6379> BF.DEBUG urls
1) "size:0"
2) "bytes:198 bits:1584 hashes:11 hashwidth:64 capacity:100 size:0 ratio:0.0005"
```

**Comment by ashtul** [comment]
@starzou 
Note you may use the flag `NONSCALING` to save space. The flag will prevent the filter from scaling but will use one less hash function for the filter which translates to saving of 1.4 bits per element/URL.
If you have a clear idea of how many URLs you are going to insert, you should use it. Even if the number differ by 10-20%, you might be better off taking the upper limit.

**Comment by starzou** [comment]
Awesome! Thank you again. @ashtul 

```
127.0.0.1:6379> BF.RESERVE urls 0.01 100 NONSCALING
OK
127.0.0.1:6379> BF.DEBUG urls
1) "size:0"
2) "bytes:120 bits:960 hashes:7 hashwidth:64 capacity:100 size:0 ratio:0.01"
```

```
127.0.0.1:6379> BF.RESERVE urls 0.001 100 NONSCALING
OK
127.0.0.1:6379> BF.DEBUG urls
1) "size:0"
2) "bytes:180 bits:1440 hashes:10 hashwidth:64 capacity:100 size:0 ratio:0.001"
```
