### ISSUE TITLE
StackExchange.Redis extension methods

### ISSUE THREAD

**Issue by naile** [RedisBloom/RedisBloom#233]
Hey, love the module, it's really easy to work with and a great addition to the Redis ecosystem!

Recently found myself needing to use it in .NET Core with the [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis) Client.

Couldn't find any ready to use implementation so I put together some extension methods and implemented Bloom Filter and Top-K.

Not sure but maybe it's useful for someone else if you wanna stick it in the "Client libraries" list?
https://gist.github.com/naile/96de4e9548c7b5fd6c0614009ffec755

**Comment by ashtul** [comment]
@naile 
The extension looks great. 
Can you please add some tests and test to describe how to use it?

**Comment by naile** [comment]
@ashtul I think for a .NET developer how to use [extension methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods) is self-explanatory. You'd just paste this class (or just the methods you need) into your solution and the methods will be available on the StackExchange.Redis interface.

I can stick a small readme with some usage examples and add links to StackeEchange.Redis and Redisbloom documentation

**Comment by ashtul** [comment]
@naile - A small readme would be fine then.
Do you want to create the PR for your client?

I hope you will add the Cuckoo and CMS commands in the future :)
