### ISSUE TITLE
NONSCALING not work in BF.RESERVE 

### ISSUE THREAD

**Issue by zwzw911** [RedisBloom/RedisBloom#242]
Try to create a bloom filter with NONSCALING, but BF.INFO show Expansion rate equal to default value 2
127.0.0.1:6379> **bf.reserve a 0.0001 10000**
OK
127.0.0.1:6379> bf.info a
 1) Capacity
 2) (integer) 10000
 3) Size
 4) (integer) 25918
 5) Number of filters
 6) (integer) 1
 7) Number of items inserted
 8) (integer) 0
 9) **Expansion rate**  
10) (integer) **2**    
         
127.0.0.1:6379> **bf.reserve b 0.0001 10000 NONSCALING**   
OK  
127.0.0.1:6379> bf.info b  
 1) Capacity
 2) (integer) 10000
 3) Size
 4) (integer) 24115
 5) Number of filters
 6) (integer) 1
 7) Number of items inserted
 8) (integer) 0
 9) **Expansion rate**
10) (integer)**2**

**Comment by ashtul** [comment]
@zwzw911 
Thanks for the issue. Indeed, the value should be change to 0 or (nil). 
But the filter will perform correctly and not add a sub filter once the initial filter is full. 
Please note that the size of the NONSCALING filter is smaller since we use one less hash than in the scaling version.

**Comment by zwzw911** [comment]
@ashtul 
Thanks for your clarify, I an glad to knon it is just a dispaly error, and won't affect the real action.
