### ISSUE TITLE
redis-dump can not be dump this type, how to fix it?

### ISSUE THREAD

**Issue by ren-jimmy** [RedisBloom/RedisBloom#253]
![image](https://user-images.githubusercontent.com/25098996/97948283-0d155300-1dcb-11eb-9975-56ff2e12734f.png)

**Comment by ashtul** [comment]
@ren-jimmy - RedisBloom has a special dump command, BF.SCANDUMP, since size of filter can go beyond the limit of 512MB. 

You can read about it at: https://oss.redislabs.com/redisbloom/Bloom_Commands/

**Comment by ashtul** [comment]
@ren-jimmy, do you need any further assistance on this issue?
