### ISSUE TITLE
cuckoo filter initialization parameters

### ISSUE THREAD

**Issue by qingping209** [RedisBloom/RedisBloom#259]
testBulkDel of test-cuckoo.c will fail if expansion was set to 2 instead of 1.  why was that? 

![image](https://user-images.githubusercontent.com/11344292/101300462-a32c1580-3870-11eb-8671-a2681fe44010.png)

![image](https://user-images.githubusercontent.com/11344292/101300475-af17d780-3870-11eb-8d00-63e19b8a5b1b.png)

does the correctness depend on how the filter is initialized ?

**Comment by qingping209** [comment]
@ashtul

**Comment by ashtul** [comment]
@qingping209 , thank you for the issue.
This seems odd. I'll take a look.

**Comment by qingping209** [comment]
> @qingping209 , thank you for the issue.
> This seems odd. I'll take a look.

and it seems like *expansion* is the only the variable that would fail the test. and also I noticed in rebloom.c the default value of expansion is also 1.   

![image](https://user-images.githubusercontent.com/11344292/101320415-af2ecc00-389e-11eb-8b41-94053fb7e7c6.png)

**Comment by qingping209** [comment]
any update on this ? @ashtul

**Comment by qingping209** [comment]
fixed by #260
