### ISSUE TITLE
tdigest.h file not found

### ISSUE THREAD

**Issue by asyncins** [RedisBloom/RedisBloom#311]
Hi ～ I have a problem:

```
> make
RedisBloom/src/rm_tdigest.c:5:10: fatal error: 'tdigest.h' file not found
```

where is tdigest.h?

**Comment by filipecosta90** [comment]
@asyncins the tdigest header is present on a submodule so you just need to init and update it. 

here are two examples of how to do it:

**option 1:**
```
git clone https://github.com/RedisBloom/RedisBloom.git
cd RedisBloom
git submodule init
git submodule update
make
```

**option 2:**
```
git clone --recursive https://github.com/RedisBloom/RedisBloom.git
cd RedisBloom
make
```

Sorry if that was not clear. The documentation has been updated on the master docs here: https://oss.redislabs.com/redisbloom/master/Quick_Start/#building but it's still not in the default documentation given we've not yet released an official version with it.
