### ISSUE TITLE
Need a command to return all TOP-K entries with their counts

### ISSUE THREAD

**Issue by let4be** [RedisBloom/RedisBloom#324]
Now I could do this using 2 queries(TOPK.LIST + TOPK.COUNT) but while doing so some items could have been expelled which is non ideal...

**Comment by gkorland** [comment]
You can use Redis transactions

**Comment by let4be** [comment]
afaik transactions won't do the job, this can be solved only by LUA/Redis modules which may be a bit too much... it would be nice to have more flexibility right out-of-the-box

I already solved this task by writing a custom redis module, turned out I needed a bunch of other logic that is better done on redis side.

**Comment by let4be** [comment]
I just figured since the data is already here and can be accessed relatively cheap(in a constant time) it might be nice to provide a convinient interface to this data from the RedisBloom side

**Comment by ashtul** [comment]
@let4be the `count` you receive with `TOPK.COUNT` is not accurate and is lower or even much lower than the real count. We should consider removing it altogether. Since it might mistaken users.

**Comment by let4be** [comment]
I'm not interested in an exact count, however an approximation for most heavy hitters is nice to have
What kind of innacuracy are we talking about? Is it configurable?

**Comment by ashtul** [comment]
@let4be very soon the number has no relationship with the real count. 
The algorithm not only rejects some entries but also reduces the existing count. So between two numbers, you can get a hint of who appears more but it is very loose.

**Comment by let4be** [comment]
Still how bad it is, I read that top-k never overcounts
Do all elements in the top-k bear similar degree of an error?
