### ISSUE TITLE
trouble with  Launch RedisBloom with Docker

### ISSUE THREAD

**Issue by l1725821492** [RedisBloom/RedisBloom#345]
i want to use aof with redis ,but have met a trouble when i add -`-appendonly yes` to open aof the  bloom module not load,
close aof the bloom module is correct load .
![image](https://user-images.githubusercontent.com/49476921/128986956-bd107eb1-4230-41d9-8976-a35ad0b44b81.png)
![image](https://user-images.githubusercontent.com/49476921/128986971-3071aaa2-80f2-4a07-bdba-581ed40406ce.png)

**Comment by filipecosta90** [comment]
Hi there @l1725821492 , as you can see the last log lines, the module is located at `/usr/lib/redis/modules/redisbloom.so`. 
You can achieve the outcome you want as follow: 
```
$ docker run -p 6379:6379 redislabs/rebloom:edge redis-server --appendonly yes  --loadmodule /usr/lib/redis/modules/redisbloom.so
```
