### ISSUE TITLE
Are Redisbloom commands blocking in nature?

### ISSUE THREAD

**Issue by mehuled** [RedisBloom/RedisBloom#351]
I have to modify a BloomFilter `BF.MADD` as well as evaluate if elements exist in the BloomFIlter parallelly `BF.EXISTS` on a Redis in cluster mode, Would this have a performance effect?

**Comment by mehuled** [comment]
For more context, I could not find any documentation that suggests that however, I have come to realize that a lot of Redis commands are blocking in nature.

Since I have to modify as well as add elements to the same bf simultaneously, in case of `BF.ADD` blocking `BF.EXISTS` I'll need to create a copy of a BloomFilter for each addition of an element which does not seems to be a ideal way to do it.

Would appreciate any more info on this, thanks!

**Comment by ashtul** [comment]
Hi @mehuled ,
Yes. RedisBloom commands are blocking.
What do you mean by `modify as well as add`?
Also, both BF.ADD and BF.MADD will return 1/0 per element if it existed or not. Does this help in any way?

**Comment by mehuled** [comment]
Hey @ashtul apologies, I meant `add as well as check if exists on the same bf simultaneously` through different clients, would this be a blocking operation?

I mean would it be the case that while `BF.ADD` is being performed on a bf, `BF.EXISTS` will be blocked on the same bf even by other clients as well untill `BF.ADD` is completed?


Could you also possibly elaborate the definition of Blocking here? I mean is it blocking the client, the server or the BloomFilter data structure? 

Much appreciated, thanks!

**Comment by ashtul** [comment]
Redis is a single thread server and RedisBloom has no internal multithreading therefore any command will block the server (and data structure) until finished.

**Comment by mehuled** [comment]
AC
