### ISSUE TITLE
TDIGEST not found when running redislabs/rebloom:latest with Docker

### ISSUE THREAD

**Issue by cevenrokt** [RedisBloom/RedisBloom#379]
Hi,

I'm interested in using the new TDIGEST bloom filter. I thought it was available but my attempt to create a filter failed.

**Commands to reproduce:**

`docker run -p 6379:6379 --name redis-redisbloom redislabs/rebloom:latest`
`redis-cli` (separate window)
```
127.0.0.1:6379> TDIGEST.CREATE t-digest 100
(error) ERR unknown command `TDIGEST.CREATE`, with args beginning with: `t-digest`, `100`,
```
Can you shed some light on why I am getting `(error) ERR unknown command` `TDIGEST.CREATE`?

![Screen Shot 2021-11-18 at 12 28 08 pm](https://user-images.githubusercontent.com/83316643/142334857-422849be-bc9a-4b2f-b777-5842ab838378.png)

**Comment by filipecosta90** [comment]
Hi there @cevenrokt, the TDIGEST datastructure will be available on the next release of RedisBloom ( v2.4 ), meaning for now it's only on master ( repo ) and in the `redislabs/rebloom:edge` docker image. 
You can try it with:
```
docker run -p 6379:6379 --name redis-redisbloom redislabs/rebloom:edge
127.0.0.1:6379> TDIGEST.CREATE key 100
OK
```

Feel free to reopen the issue if the above fix did not work.

**Comment by cevenrokt** [comment]
Thank you @filipecosta90 ! Is there an ETA on the release date? My team is very eager to try it out

**Comment by gkorland** [comment]
We don't a final release date yet, but it should be in the near future, we were looking to gather more feedback before we release it officially, can you please try it and give your feedback?
