### ISSUE TITLE
Does it support Redis Cluster Nodes with Sharding?

### ISSUE THREAD

**Issue by Taymindis** [RedisBloom/RedisBloom#388]
We have clustered Redis nodes. I am wondering how is it spreading the nodes for filter and collect back? is it done from client-side or?

**Comment by LiorKogan** [comment]
There is no need for a single RedisBloom data structure to grow beyond a single shard. 
The whole point of these data structures is to be extremely memory-efficient. This comes at the price of introducing a small (controllable) error of course.

Each RedisBloom data structure is held under a single Redis key, hence - stored in a single shard.
Different RedisBloom data structures can be stored in different shards.

**Comment by jagadeeshmarali** [comment]
I have the same question as @Taymindis  and 
@LiorKogan when i use redis pub sub on redis bloom container it is exceeding the output buffer limits of 32mb, when there is very low latency.

`Client id=56146 addr=172.27.0.3:49270 fd=10 name= age=5 idle=0 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=257 omem=33576984 tot-mem=33597488 events=rw cmd=subscribe user=default scheduled to be closed ASAP for overcoming of output buffer limits.`

Am i doing mistake?.

If i want to cluster redis bloom nodes can i follow the same process as redis cluster does?
