### ISSUE TITLE
Cuckoo Filter Documentation refers to `CF.CHECK` command which doesn't exist?

### ISSUE THREAD

**Issue by simonprickett** [RedisBloom/RedisBloom#390]
In the documentation for the `CF.ADDNX` command, it says:

> This command is equivalent to a `CF.CHECK` + `CF.ADD` command

`CF.CHECK` does not appear to exist as a command.

The documentation for `CF.INSERTNX` also mentions `CF.CHECK`.

**Comment by LiorKogan** [comment]
Fixed. Thank you.
