### ISSUE TITLE
cuckoo filter used too much memory

### ISSUE THREAD

**Issue by npchp110** [RedisBloom/RedisBloom#41]
Hi, I'm using the cuckoo filter as below:
127.0.0.1:6379[1]> keys *
1) "psua01"
2) "dialog_c_token"
3) "pscs01"
4) "pslg01"
127.0.0.1:6379[1]> cf.debug dialog_c_token
"bktsize:2 buckets:536870912 items:6125119 deletes:0 filters:23"
127.0.0.1:6379[1]> get psua01
"1cf4e9bb"
127.0.0.1:6379[1]> get pscs01
"15b3a447"
127.0.0.1:6379[1]> get pslg01
"72df15a5"

this cuckoo filter consumed 23GB memory，why it ate so much memory?

127.0.0.1:6379> info
# Server
redis_version:4.0.0
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d67dbd36e54575ba
redis_mode:standalone
os:Linux 3.10.0-229.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:23143
run_id:8035b890658071e85ee281af622a00c3145e3a0e
tcp_port:6379
uptime_in_seconds:218
uptime_in_days:0
hz:10
lru_clock:505611
executable:/usr/local/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:313
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:220

# Memory
used_memory:24709106272
used_memory_human:23.01G
used_memory_rss:24743956480
used_memory_rss_human:23.04G
used_memory_peak:24728498696
used_memory_peak_human:23.03G
used_memory_peak_perc:99.92%
used_memory_overhead:10548714
used_memory_startup:487192
used_memory_dataset:24698557558
used_memory_dataset_perc:99.96%
total_system_memory:33566187520
total_system_memory_human:31.26G
used_memory_lua:37888
used_memory_lua_human:37.00K
maxmemory:25769803776
maxmemory_human:24.00G
maxmemory_policy:noeviction
mem_fragmentation_ratio:1.00
mem_allocator:jemalloc-4.0.3
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:500
rdb_bgsave_in_progress:0
rdb_last_save_time:1527232049
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:314
total_commands_processed:26187
instantaneous_ops_per_sec:126
total_net_input_bytes:1474248
total_net_output_bytes:423442
instantaneous_input_kbps:5.58
instantaneous_output_kbps:0.72
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
evicted_keys:0
keyspace_hits:498
keyspace_misses:1
pubsub_channels:3
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:a8200ae6c7c0411ad95043e94bf1035270432824
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:7.11
used_cpu_user:50.34
used_cpu_sys_children:0.00
used_cpu_user_children:0.00

# Cluster
cluster_enabled:0

# Keyspace
db1:keys=4,expires=0,avg_ttl=0

**Comment by mnunberg** [comment]
Are you allocating your cuckoo filter for the correct number of items you’re planning to store?

**Comment by ashtul** [comment]
No followup
