### ISSUE TITLE
Documentation - Suggested item hash functions.

### ISSUE THREAD

**Issue by devspyrosv** [RedisBloom/RedisBloom#47]
Hello! I have been using rebloom successfully for some months now.

One of the questions I have had back from when I first heard about this wonderful project, was which is the best or suggested way to hash an item before inserting it into the filter.

I believe it would be really helpful to have some hints in the docs or even better some pseudo code examples.

Also what do you think about using sha256?

Thank you for this project!

EDIT:
 PS: It would be nice to have an equation calculating the total RAM needed for a given item number and a false positive probability. For example I have calculated that for a capacity of 1000000000 items and an error probability of 0.000001 the size of the produced bloom filter is somewhere around 4GB.

**Comment by ashtul** [comment]
@devspyrosv, the hash function used is MurmurHash2 which can be found in the contrib folder.

Memory allocated = abs(log(error) / ln(2)^2)
