### ISSUE TITLE
2.2.15 make fail

### ISSUE THREAD

**Issue by huangsonglie** [RedisBloom/RedisBloom#472]
/root/RedisBloom-2.2.15/src/rm_tdigest.c:19:10: fatal error: tdigest.h: 没有那个文件或目录
 #include "tdigest.h"
          ^~~~~~~~~~~
compilation terminated.
make: *** [/root/RedisBloom-2.2.15/src/rm_tdigest.o] 错误 1

**Comment by LiorKogan** [comment]
Thank you.
This should have not happened.
We will release 2.2.17 soon instead.

**Comment by gkorland** [comment]
@huangsonglie the tag was fixed, please try to use tag: ver2.2.15
