### ISSUE TITLE
proposal: Add bf.Card command for bloom filter

### ISSUE THREAD

**Issue by MakDon** [RedisBloom/RedisBloom#488]
`BF.CARD` returns the cardinality (number of items inserted) of the bloom filter  stored at key.

## Usage

```
redis> BF.ADD item1 item_foo
(integer) 1
redis9> BF.CARD item1
(integer) 1
redis9> BF.CARD item_new
(integer) 0
```

## Why not BF.INFO

- BF.INFO returns all the info about the filter. But BF.CARD only returns the cardinality.
- BF.INFO returns error when key is not existed. But BF.CARD return 0. (just like [scard][scard], [zcard][zcard] does)

## Why not name it as "bf.count"

In [Another issue](#389 ), @simonprickett suppose to use a command called `bf.count`.    
But there's a command call [cf.count][cf.count], which `Returns the number of times an item may be in the filter`
So it maybe confusing that we use `bf.count` here to return the cardinality of the filter.

## When we need BF.CARD

When we want to use BF as a estimated ZSET.

Assume that some users bought some items, and we want to count "how many users bought a SKU":
```
UserA bought SKU-A, SKU-B, SKU-C,
UserB bought SKU-B
UserC bought SKU-A, SKU-C
UserD bought SKU-D
...
```

And we use the SKU-ID as key, and insert the userID into `how:many:users:bought:SKU-ID`
Then walk through all the SKUs to get the cardinality:
```
BF.CARD how:many:users:bought:SKU-A
BF.CARD how:many:users:bought:SKU-B
BF.CARD how:many:users:bought:SKU-C
BF.CARD how:many:users:bought:SKU-D
BF.CARD how:many:users:bought:SKU-E
```

If we use `bf.INFO` instead of `bf.CARD`, when no one bought SKU-E, it will return error key not exist instead of 0
So we have to check the existence before we use `bf.INFO`.       
`bf.CARD` returns 0 so we no need to `EXIST key` before we query the cardinality.

## Why not BF.INFO {key} [CAPACITY|SIZE|FILTERS|ITEMS|

It is a good idea, but `bf.INFO` returns error when key not exists.
For backward compatibility, I propose use `bf.CARD` instead.

[scard]: https://redis.io/commands/scard/
[zcard]: https://redis.io/commands/zcard/
[cf.count]: https://redis.io/commands/cf.count/

**Comment by ashtul** [comment]
@MakDon Thank you for the proposal.
An issue that both BF.INFO and BF.CARD would have is, if UserA is entered twice, it will be counted twice, as there is no way to distinguish between existing and new items.

Did you consider using HyperLogLog and having HLL per SKU?

**Comment by MakDon** [comment]
> @MakDon Thank you for the proposal. An issue that both BF.INFO and BF.CARD would have is, if UserA is entered twice, it will be counted twice, as there is no way to distinguish between existing and new items.
> 
> Did you consider using HyperLogLog and having HLL per SKU?

Thanks for your advise. 

I tried to insert multiple times, the `bf.CARD` returns the correct answer(without counted it twice). I am not so familiar with `Bloom Filter` that i can not figure out why:

```
127.0.0.1:6379> bf.Add skuA usr1
(integer) 1
127.0.0.1:6379> bf.Add skuA usr1
(integer) 0
127.0.0.1:6379> bf.Add skuA usr1
(integer) 0
127.0.0.1:6379> bf.Add skuA usr1
(integer) 0
127.0.0.1:6379> bf.Add skuA usr1
(integer) 0
127.0.0.1:6379> bf.card skuA
(integer) 1
127.0.0.1:6379> bf.Add skuA usr2
(integer) 1
127.0.0.1:6379> bf.Add skuA usr2
(integer) 0
127.0.0.1:6379> bf.Add skuA usr2
(integer) 0
127.0.0.1:6379> bf.Add skuA usr2
(integer) 0
127.0.0.1:6379> bf.card skuA
(integer) 2
```

And IMO, it is still worth discussing, as a shortcut for `BF.INFO` :D

**Comment by simonprickett** [comment]
Agree that `CARD` makes more sense, that multiple insertions shouldn't count more than once and that this is worth continuing with.

**Comment by ashtul** [comment]
@MakDon You are right!! We increase bf->size only if we set at least one bit. This means the cardinality would be a rough estimate, as you suggested. We will consider your PR, which is nice and only missing a small test :)

Out of curiosity, Is there a reason why you do not use HyperLogLog, which would be more compact and accurate?

**Comment by simonprickett** [comment]
For me having a count on Bloom gives you a two for one structure... you can check membership and approximate cardinality in one data structure.

**Comment by MakDon** [comment]
> @MakDon You are right!! We increase bf->size only if we set at least one bit. This means the cardinality would be a rough estimate, as you suggested. We will consider your PR, which is nice and only missing a small test :)
> 
> Out of curiosity, Is there a reason why you do not use HyperLogLog, which would be more compact and accurate?

I have the same reason as @simonprickett 's. It is more convenient in my scenarios compared to HyperLogLog.

**Comment by MakDon** [comment]
> @MakDon You are right!! We increase bf->size only if we set at least one bit. This means the cardinality would be a rough estimate, as you suggested. We will consider your PR, which is nice and only missing a small test :)
> 
> Out of curiosity, Is there a reason why you do not use HyperLogLog, which would be more compact and accurate?

Okay! I will finish the tests ASAP.

**Comment by LiorKogan** [comment]
See #489
