### ISSUE TITLE
License needs to be changed to continue to be listed at Redis Modules

### ISSUE THREAD

**Issue by brennanfee** [RedisBloom/RedisBloom#51]
This has got to be fixed in order to actually be open source. The Redis modules site explicitly states, "Only modules under an OSI approved license are listed here." Commons Clause IS NOT OSI APPROVED.

**Comment by itamarhaber** [comment]
Hello @brennanfee 

Thank you for taking the time to open this issue across multiple repositories. I'll keep this issue open until it is resolved.

**Comment by ashtul** [comment]
RedisBloom is available under REDIS SOURCE AVAILABLE LICENSE AGREEMENT
