### ISSUE TITLE
CF.INFO

### ISSUE THREAD

**Issue by 642182468** [RedisBloom/RedisBloom#517]
What does "Number of filter" mean.Why capacity = 16,but can insert more than 16 elements,and filterNum will be +1

**Comment by ashtul** [comment]
The filter adds more subfilters and therefore has the capacity for additional elements. 
Please note, on Cuckoo filters, the error rate will increase with the number of filters, while with our bloom implementation, the error rate will remain constant.

**Comment by 642182468** [comment]
Thank you for your reply. In addition, in the source code, I found that CuckooFilter-CompactSingle method will be invoked  to migrate new filter elements and recycle filters when the deletion counter of Cuckoo Filter reaches 10% of the total number of elements. Does the execution of this method mean that the  whole Redis will not be able to provide other services during this period.

**Comment by ashtul** [comment]
Yes. The compacting operation happens on the main thread and may lock the server if the filter is very large.
