### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by bodevone** [RedisBloom/RedisBloom#525]
All of the commands in RedisBloom have broken links in the documentation.

For example, at the page https://redis.io/commands/bf.exists/ when you press at `Bloom 1.0.0` it leads to https://redis.io/docs/stack/bf which does not exist.
It probably should forward to https://redis.io/docs/stack/bloom/.

From what I am guessing `group` field in `commands.json` is used for the link.

**Comment by LiorKogan** [comment]
Thank you. We'll take care of this.

**Comment by nermiller** [comment]
@itamarhaber

**Comment by bodevone** [comment]
Looks likes it is fixed now
