### ISSUE TITLE
Does Cuckoo filter has deadlock or false misses issue

### ISSUE THREAD

**Issue by qneo26** [RedisBloom/RedisBloom#534]
According to  [this artical](https://lrita.github.io/images/posts/datastructure/MemC3-Compact-and-Concurrent-MemCache-with-Dumber-Caching-and-Smarter-Hashing.pdf) ,cockoo hash-like algorithms have two major issues:

>  There are two major obstacles to making the sequential
> cuckoo hashing algorithm concurrent:
> 1. Deadlock risk (writer/writer): An Insert may modify a set of buckets when moving the keys along the
> cuckoo path until one key lands in an available bucket.
> It is not known before swapping the keys how many
> and which buckets will be modified, because each displaced key depends on the one previously kicked out.
> Standard techniques to make Insert atomic and
> avoid deadlock, such as acquiring all necessary locks
> in advance, are therefore not obviously applicable.
> 2. False misses (reader/writer): After a key is kicked
> out of its original bucket but before it is inserted to its
> alternate location, this key is unreachable from both
> buckets and temporarily unavailable. If Insert is
> not atomic, a reader may complete a Lookup and
> return a false miss during a key’s unavailable time.
> E.g., in Figure 3, after replacing b with a at bucket
> 4, but before b relocates to bucket 1, b appears at
> neither bucket in the table. A reader looking up b at
> this moment may return negative results
<img width="297" alt="image" src="https://user-images.githubusercontent.com/12489009/189316314-aa01db2f-8024-473f-9a6d-a37facc2f445.png">
does this Cuckoo filter implemention  has the same problems ?

i did not find any code snippet in cuckoo.c  aiming to solve those problems

**Comment by ashtul** [comment]
@qneo26 RedisBloom as the rest of redis ecosystem is single threaded. 
All inserts, queries and deletions are done as an atomic operation.

**Comment by qneo26** [comment]
problem solved
