### ISSUE TITLE
bf.exists cannot differentiate  between no bloomfilter(key) and no item in BF

### ISSUE THREAD

**Issue by yx621** [RedisBloom/RedisBloom#54]
Seems the bf.exists command just return 0 for the case with no bloomfilter exists and no value in bloom filter. So to ensure an element is indeed not in bloomfilter, first need to verify the bloom filter keys exists and then the value is indeed not in bloomfilter, which is corresponding to 2 redis operation. 

Is there other ways to deal with this situation? 

Leave a comment if I did not use it properly.

**Comment by mnunberg** [comment]
I think this was actually implemented as a feature request, where a user was getting annoyed at him getting an error or a 0 back depending on whether or not the filter existed.
