### ISSUE TITLE
Time To Live

### ISSUE THREAD

**Issue by Philmod** [RedisBloom/RedisBloom#56]
Hey,

Is it possible to create a filter (`BF.RESERVE`) with a TTL? 

In my case, I want to create a filter for each of the active users, and make sure Redis cleans up least active user filters when needed. https://redis.io/topics/lru-cache

Thanks,
Philippe

**Comment by itamarhaber** [comment]
Hello @Philmod 

You can expire a filter with the [`EXPIRE`](https://redis.io/commands/expire) command. Currently, there is no single command to reserve and expire the filter, so you'll have to first reserve and then expire the key.
