### ISSUE TITLE
Unable to load RedisBloom

### ISSUE THREAD

**Issue by pk-vungle** [RedisBloom/RedisBloom#590]
Hi, I'm trying to load RedisBloom but failed with error message:
1519:M 18 Nov 2022 08:51:40.139 * <bf> RedisBloom version 99.99.99 (Git=unknown)
1519:M 18 Nov 2022 08:51:40.139 # Module /var/lib/redis/modules/redisbloom.so initialization failed. Module not loaded
1519:M 18 Nov 2022 08:51:40.139 # Can't load module from /var/lib/redis/modules/redisbloom.so: server aborting

What I did:
1. place redisbloom.so in /var/lib/redis/modules
2. in redis.conf, use: loadmodule  /var/lib/redis/modules/redisbloom.so 
3. start redis from systemd, systemctl start redis

I also tried building it but make setup gave me this error
root@2c246ff6f7bf:/RedisBloom# make setup
make: *** No rule to make target 'setup'.  Stop.

Am I missing dependencies?

**Comment by gkorland** [comment]
Which version of Redis are you using?
Which operation system?

**Comment by pk-vungle** [comment]
I'm using Redis 6.2.7 in cluster mode on Ubuntu 22.04. I have also cuckoofilter module loaded. I found out that with that module loaded, I can't load Redisbloom. Is this usually the case?

**Comment by pk-vungle** [comment]
Hi, I manage to load RedisBloom once I removed cuckoo Filter. It seems like I cannot load both together. The one I have is compiled from https://github.com/kristoff-it/redis-cuckoofilter

**Comment by LiorKogan** [comment]
@pk-vungle 
It seems that this module register the CF commands for Cuckoo. Same as we do in RedisBloom. This may be the reason.
