### ISSUE TITLE
The bitmap scales by 4 times each scale,  can i specify this param when loading redisbloom or using BF.RESERVE? 

### ISSUE THREAD

**Issue by chxfantasy** [RedisBloom/RedisBloom#60]
1) "size:975"
2) "bytes:4 bits:32 hashes:10 hashwidth:64 capacity:2 size:2 ratio:0.001"
3) "bytes:16 bits:128 hashes:12 hashwidth:64 capacity:7 size:7 ratio:0.00025"
4) "bytes:64 bits:512 hashes:15 hashwidth:64 capacity:23 size:23 ratio:3.125e-05"
5) "bytes:256 bits:2048 hashes:19 hashwidth:64 capacity:74 size:74 ratio:1.95313e-06"
6) "bytes:1024 bits:8192 hashes:24 hashwidth:64 capacity:236 size:236 ratio:6.10352e-08"
7) "bytes:4096 bits:32768 hashes:30 hashwidth:64 capacity:757 size:633 ratio:9.53674e-10”

when the memory scales, 4 times the last memory is acquired.
when using small bitmap, its ok,
if i am using redisbloom with 10billion keys, i can reserve 10billion capacity when create this filter, but what if the (10 billion+1) key is inserted?  i think no one can bare 4 times more memory.

can i specify this scaling param ?
Or any other suggestions?

**Comment by CBaquero** [comment]
Hi,

Not sure how the module handles it and if a scaling parameter is supported. But in theory it should be ok to have such a parameter.

The core part that ensures the overall properties is the false positive probability that needs to be more tight with each new filter. The capacity itself can be configurable. For normal use cases making bigger and bigger capacity filters ensures that not a lot of filters need to be created.

-----
Carlos Baquero
HASLab / INESC TEC &
Universidade do Minho,
Portugal

cbm@di.uminho.pt
http://haslab.uminho.pt/cbm/

**Comment by chxfantasy** [comment]
Thanks for your answer.




> Hi, Not sure how the module handles it and if a scaling parameter is supported. But in theory it should be ok to have such a parameter. The core part that ensures the overall properties is the false positive probability that needs to be more tight with each new filter. The capacity itself can be configurable. For normal use cases making bigger and bigger capacity filters ensures that not a lot of filters need to be created.
> […](#)
> ----- Carlos Baquero HASLab / INESC TEC & Universidade do Minho, Portugal cbm@di.uminho.pt http://haslab.uminho.pt/cbm/
> On 12 Mar 2019, at 06:55, chxfantasy ***@***.***> wrote: • "size:975" • "bytes:4 bits:32 hashes:10 hashwidth:64 capacity:2 size:2 ratio:0.001" • "bytes:16 bits:128 hashes:12 hashwidth:64 capacity:7 size:7 ratio:0.00025" • "bytes:64 bits:512 hashes:15 hashwidth:64 capacity:23 size:23 ratio:3.125e-05" • "bytes:256 bits:2048 hashes:19 hashwidth:64 capacity:74 size:74 ratio:1.95313e-06" • "bytes:1024 bits:8192 hashes:24 hashwidth:64 capacity:236 size:236 ratio:6.10352e-08" • "bytes:4096 bits:32768 hashes:30 hashwidth:64 capacity:757 size:633 ratio:9.53674e-10” when the memory scales, 4 times the last memory is acquired. when using small bitmap, its ok, if i am using redisbloom with 10billion keys, i can reserve 10billion capacity when create this filter, but what if the (10 billion+1) key is inserted? i think no one can bare 4 times more memory. can i specify this scaling param ? Or any other suggestions? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mnunberg** [comment]
We can definitely add this as a parameter

**Comment by ashtul** [comment]
@chxfantasy  @CBaquero 
Just a note, Bloom auto-scaling has more implications than just memory. It is always advised to reserve capacity in quantities that will reflect their use.
I hope to get to this soon.

**Comment by ashtul** [comment]
#152 
currently set at 2

**Comment by ashtul** [comment]
@chxfantasy 
#153

**Comment by ashtul** [comment]
@chxfantasy 
We have finally got to fix this.
* PR #153 added an `expansion` option
* PR #155 changed behavior which rounded size to the next `pow(2,x)`.

Thank you for bringing it to our attention.
