### ISSUE TITLE
Cuckoo Filter memory usage reporting

### ISSUE THREAD

**Issue by erikcw** [RedisBloom/RedisBloom#609]
There doesn't appear to be a way to return how much memory a cuckoo filter is consuming:

```
127.0.0.1:6378[2]> CF.INFO test_filter_cuckoo
 1) Size
 2) (integer) 8589934664
 3) Number of buckets
 4) (integer) 2147483648
 5) Number of filters
 6) (integer) 2
 7) Number of items inserted
 8) (integer) 141679676
 9) Number of items deleted
10) (integer) 0
11) Bucket size
12) (integer) 2
13) Expansion rate
14) (integer) 1
15) Max iterations
16) (integer) 20

127.0.0.1:6378[2]> MEMORY USAGE  test_filter_cuckoo
(integer) 120
127.0.0.1:6378[2]>
```

Bloom filters return their `Size` from `BF.INFO`.  So I was expecting `CF.INFO` to include similar information.  `MEMORY USAGE` does not seem like it could possibly be correct in this case.  My Cuckoo Filter is sized with a capacity of `2^32`.

**Comment by ashtul** [comment]
@erikcw thank you for the info.
I can reproduce the error and it occur b/c we have used uint32 for `numBuckets` in the `SubCF` struct.
We will post a fix soon.
