### ISSUE TITLE
Why must this be set BREW_AS_ROOT=1？

### ISSUE THREAD

**Issue by MrYbo** [RedisBloom/RedisBloom#669]
<img width="647" alt="image" src="https://github.com/RedisBloom/RedisBloom/assets/23352300/0ee906ec-68a7-468e-a92d-b550e37ceb10">

Why do you have to use root privileges to install this plugin, this is really rubbish

**Comment by rafie** [comment]
On macOS, you don't use `sudo` to invoke `./sbin/setup`.
It says `Cannot run as root`, doesn't it?
