### ISSUE TITLE
Bloom filter Error

### ISSUE THREAD

**Issue by DKdev117** [RedisBloom/RedisBloom#681]
=> Hi everyone, I am working on the bloom filter. when I create a filter, it throws some error like this ["ERR unknown command 'BF.ADD', with args beginning with: 'new filter' 'photo']

=> Please solve this issue

=>Images

![Screenshot 2023-10-05 212318](https://github.com/RedisBloom/RedisBloom/assets/131585729/d9bdcf62-e6b3-447d-a12e-535c7aa1c707)

![Screenshot 2023-10-05 212450](https://github.com/RedisBloom/RedisBloom/assets/131585729/0839f56d-d1d8-4835-b705-878bd5b7ad9c)

![Screenshot 2023-10-05 212532](https://github.com/RedisBloom/RedisBloom/assets/131585729/1115fb79-ea22-4d50-8aad-2b333028a489)

![Screenshot 2023-10-05 212618](https://github.com/RedisBloom/RedisBloom/assets/131585729/21f06470-a09d-4a54-bc2e-542489fc0641)

**Comment by LiorKogan** [comment]
It seems that the RedisBloom module is not installed on your Redis server. You can try to use Redis Stack.

**Comment by DKdev117** [comment]
@LiorKogan thank you

**Comment by DKdev117** [comment]
how to install the bloom filter module please guide me

**Comment by LiorKogan** [comment]
If you are using Redis Open Source you'll have to [build the module from its source code](https://github.com/RedisBloom/RedisBloom#build-it-yourself).

A much simpler solution would be to use [Redis Stack](https://redis.io/docs/about/about-stack/) instead. Redis Stack bundles the following features into Redis: [JSON](https://redis.io/docs/stack/json), [Search and Query](https://redis.io/docs/stack/search), [Time Series](https://redis.io/docs/stack/timeseries), and [Probabilistic](https://redis.io/docs/stack/bloom) (Bloom). 

See [Redis Stack downloads](https://redis.io/download/#redis-stack-downloads).

**Comment by DKdev117** [comment]
> If you are using Redis Open Source you'll have to [build the module from its source code](https://github.com/RedisBloom/RedisBloom#build-it-yourself).
> 
> A much simpler solution would be to use [Redis Stack](https://redis.io/docs/about/about-stack/) instead. Redis Stack bundles the following features into Redis: [JSON](https://redis.io/docs/stack/json), [Search and Query](https://redis.io/docs/stack/search), [Time Series](https://redis.io/docs/stack/timeseries), and [Probabilistic](https://redis.io/docs/stack/bloom) (Bloom).
> 
> See [Redis Stack downloads](https://redis.io/download/#redis-stack-downloads).

thank you @LiorKogan
