### ISSUE TITLE
Redis Bloom filter auto-scale

### ISSUE THREAD

**Issue by llh12345** [RedisBloom/RedisBloom#716]
Question:
I use bloom filters to store many items. As the number of items increases, the bloom filter will expand by creating sub-filters. I found that these newly created subfilters had half the error rate of the previous subfilter. Can I specify that the error rate of the newly created sub-filter is the same as the original one? Why does the newly created sub-filter have half the error rate of the original one?

I used the bf.debug command to observe the situation of this Bloom filter
image

**Comment by llh12345** [comment]
I used the bf.debug command to observe the situation of this Bloom filter

![image](https://github.com/RedisBloom/RedisBloom/assets/43738754/daddc4ce-a8b5-4e41-85aa-ab2b49ab9a2e)

**Comment by LiorKogan** [comment]
Your observation is correct, but not your interpretation.

Quoting from [Scalable bloom filters](https://scholar.google.com/citations?view_op=view_citation&citation_for_view=NAUDTpMAAAAJ:u-x6o8ySG0sC):

> Each successive bloom filter is created with a tighter maximum error probability on a geometric progression, so that the compounded probability over the whole series converges to some wanted value, even accounting for an infinite series.

**Comment by llh12345** [comment]
> Your observation is correct, but there is a good reason for it:
> 
> Quoting from [Scalable bloom filters](https://scholar.google.com/citations?view_op=view_citation&citation_for_view=NAUDTpMAAAAJ:u-x6o8ySG0sC):
> 
> > Each successive bloom filter is created with a tighter maximum error probability on a geometric progression, so that the compounded probability over the whole series converges to some wanted value, even accounting for an infinite series.

Can I specify that the error rate of the newly created sub-filter is the same as the original one? We now see more memory usage due to lower error rates

**Comment by llh12345** [comment]
![image](https://github.com/RedisBloom/RedisBloom/assets/43738754/ae4174bd-6b03-4426-840e-251461f4a335)
thanks I see the code here
