### ISSUE TITLE
Build issue on os x 

### ISSUE THREAD

**Issue by stockholmux** [RedisBloom/RedisBloom#72]
When trying to build on MacOS Mojave 10.14.4 (18E226), I get the following errors:
```
clang: error: unknown argument: '-macosx_version_min'
clang: error: no such file or directory: '_RedisModule_OnLoad'
clang: error: no such file or directory: '10.6'
make: *** [/Users/kyledavisnew/redis/RedisBloom/rebloom.so] Error 1
```

**Comment by gkorland** [comment]
@stockholmux 
@jeffreylovitz suggested setting, can you try it?
```SHOBJ_LDFLAGS ?= -mmacosx-version-min=10.14 -bundle -undefined dynamic_lookup -ldl -lpthread```
