### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by nepu-SidneyYu** [RedisBloom/RedisBloom#781]
When id make, Why it tell me many header files multiple definition, How should I solve it？

RedisBloom-2.2.6/src/cms.o:/RedisBloom-2.2.6/src/redismodule.h:115: multiple definition of `RedisModule_Alloc'; /RedisBloom-2.2.6/src/rebloom.o:/RedisBloom-2.2.6/src/redismodule.h:115: first defined here

**Comment by tezc** [comment]
@nepu-SidneyYu 

Are you following the steps describe here: https://github.com/RedisBloom/RedisBloom/?tab=readme-ov-file#build-it-yourself

```
git clone --recursive https://github.com/RedisBloom/RedisBloom.git
cd RedisBloom
./sbin/setup
bash -l
make
```

**Comment by nepu-SidneyYu** [comment]
@tezc 
OK, I had solved it, Thank you!
