### ISSUE TITLE
docker load redisbloom.so failed

### ISSUE THREAD

**Issue by nepu-SidneyYu** [RedisBloom/RedisBloom#784]
when I try to use Docker-compose build my redisbloom, but it tell me a failure

1:M 20 Jul 2024 14:38:33.794 # Module /usr/local/lib/redis/modules/redisbloom.so failed to load: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /usr/local/lib/redis/modules/redisbloom.so)

I have searched for information asking me to try lowering a version, and I would like to know which version is correctly loaded into Docker, or if there are other solutions available

**Comment by nepu-SidneyYu** [comment]
@LiorKogan 
Must use Redis Stack? The Redis I had Inatalled by using docker pull long time ago, but now cannot pull any images In China, If must use Redis-Stack, I think Ishould try to download Redis-Stack image.(The Redis version I Had installed is 6.2.6 )

**Comment by LiorKogan** [comment]
We no longer maintain binaries or images for individual modules, but only for Redis Stack. Consider taking this opportunity to upgrade to Redis Stack 7.4 which will be released very very soon.

**Comment by nepu-SidneyYu** [comment]
@LiorKogan 
OK，I have found a way to download the redis-stack image，successfully installed and used redisbloom today.
Thank you very much,
