### ISSUE TITLE
[Q] Why CMSKetch_Info and CMSketch_Query return OK when GetCMSKey failed?

### ISSUE THREAD

**Issue by mapleFU** [RedisBloom/RedisBloom#816]
I meet this when I'm reading the code:
1. https://github.com/RedisBloom/RedisBloom/blob/567e234eece440f1ee8878f6734743842d4f92a9/src/rm_cms.c#L267
2. https://github.com/RedisBloom/RedisBloom/blob/567e234eece440f1ee8878f6734743842d4f92a9/src/rm_cms.c#L171

This two command return ok when `GetCMSKey` failed. I've gothrough the doc, and didn't find the definition for this. Is this expected?

**Comment by LiorKogan** [comment]
Generally speaking, Redis treats non-existent keys as empty containers. Similarly, SCARD and LLEN retuen 0 for a non-existent key.

**Comment by mapleFU** [comment]
Thanks!
