### ISSUE TITLE
Is it possible to set a exp time on an item?

### ISSUE THREAD

**Issue by rudmac** [RedisBloom/RedisBloom#94]
[CF.ADD|BF.ADD] {key} {item} [expiration EX seconds]

I don't know if my desires is right, but is there any plans in future to add this feature? or maybe this is not a Bloom algorithms scope.

It would be the best solution for managing web server pet tokens.

Nice jobs guys.

Cheers!

**Comment by itamarhaber** [comment]
Hello @rudmac 

Thanks for the feature request - it comes in at a most opportune moment as we've just discussed the possibility of adding to the BloomBox something like Time Decaying Bloom Filters, e.g http://ce.sharif.edu/~arambam/papers/Time-Decaying%20Bloom%20Filters%20for%20Data%20Streams%20with%20Skewed%20Distributions.pdf.

/cc @ashtul @K-Jo

**Comment by ashtul** [comment]
@rudmac, we are working now on an idea of _windowed_ Bloom Filter but it won't be by item but for all items in it.
Could this still fit your use case?

**Comment by rudmac** [comment]
Hello @ashtul and @itamarhaber, thanks for your reply.

@ashtul, this will be a great feature, but If a item receive a expiration time when its created, that will help me a lot, the filter will last forever and the items inside could have a time life. Maybe in the future you guys could think about this feature, if it fits into BloomFilter scope.

Good coding!

**Comment by ashtul** [comment]
Hi @rudmac,
Do you want complete expiration independence for each item or would pools of expirations satisfy your requirements?
I might have semi quick solution for the later but I can't say anything about the former.

**Comment by rudmac** [comment]
Hi @ashtul,

Complete expiration independence for each item is the perfect solution for my problem.

Imagine you have a website that generates a JWT token for each user logged in. This token has a expiration time, it will be valid until N hours/days, within this period, the user do not need to provide credentials anymore, for now one, all the web request must include the token that will be checked by the server before response (need to have a fast check).

If a maliciou user create a fake token (JWT token check/creation [https://jwt.io/](https://jwt.io/)) and start sending request to server, the server has to check if that token was created by it. Using that premise, I had two options, a regular database to persiste all generated tokens with a background process (or database procedure) running at least once a day to remove all expired token or a Redis. 

So, I starting thinking using Redis, after looking a Bloom Filter, to add all server generated token and have a fast check if it was server generated or not. Also realize that a deletion is needed, so I changed to the Cuckoo Filter. Until now, the perfect solution, except the fact that I still need to remove all expired token in a while.

With a complete expiration independence for each item, a single fast/reliable solution for this scenario is possible.

Maybe this problem already has a good Redis solution with some workaround, maybe not, didn't find. Comments are welcome.

Thanks for your help,

**Comment by itamarhaber** [comment]
@rudmac in that case, unless I'm missing the point, you can use Redis' plain strings with TTL for that. This should perform well even with millions of tracked tokens.

1. For every server-generated JWT, e.g. 123abc987, set a key with an expiry `SETEX 123abc987 3600 ""`.
2. To check if the JWT exists, do `EXISTS 123abc987`.

**Comment by rudmac** [comment]
@itamarhaber you got the point, that's the solution, simple that I have imagined. Perfect!

I'm doing that solution with a plus:

3. Using a key pre string to keep things organized and that's all, eg.: token:123abc987, token:432qwe123, ...

Thanks a lot,

Redis newbie ;)

**Comment by itamarhaber** [comment]
@rudmac sure, you can definitely prefix the key names with 'token:' or similar, although if all you're saving in that specific Redis database are tokens that would be kind of superfluous.

I'm also a newbie - every day is a learning experience ;)

**Comment by gkorland** [comment]
> If a maliciou user create a fake token (JWT token check/creation https://jwt.io/) and start sending request to server, the server has to check if that token was created by it.

@rudmac as I understand it the all idea of JWT is that the tokens are signed by the server and the server check if the tokens are valid (malicious or expire) by just checking the token without checking any DB.

The biggest drawback of JWT is that if the Admin want to cancel a token (e.g. when a user is disabled) it can't do that and the only way to do it, is by holding a black list of tokens that were canceled. For that you might want to use Redis or RedisBloom

**Comment by rudmac** [comment]
@gkorland,  you are correct, since jwt token are signed with public/private key. You can't impersonate it when you don't know the private key. Checking DB for the token can add an additional layer of security, maybe you are using insecure channels and want more checks.

Great point, only with some kind of persistence you can invalidate a token. Redis or RedisBloom can do the job.

A lot of learnings here,

Thank you guys

**Comment by gkorland** [comment]
```
Checking DB for the token can add an additional layer of security, maybe you are using insecure channels and want more checks.
```
Checking won't help when using insecure channel, cause even if stole the token it will pass your DB check.

**Comment by K-Jo** [comment]
I'm closing this issue and tracking the feature requirement here: https://github.com/RedisBloom/RedisBloom/issues/115
